name: api_client
description: 
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0