name: shared
description: Package that holds shared data classes across entire project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0
  intl: '>=0.15.0 <1.0.0'
  json_annotation: ^4.4.0 
  multiple_result: ^1.0.4


dev_dependencies:
  build_runner: 
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0